/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        String result  = classUnderTest.getGreeting();
        System.out.println(result);
        assertEquals(result, "Hello World!");
    }
}
